### ISSUE TITLE
Amazon quota

### ISSUE THREAD

**Issue by MartijnDwars** [MartijnDwars/grading-cloud#8]
By default, all AWS accounts have a limit of 20 running instances. Source: [Q: How many instances can I run in Amazon EC2?](http://aws.amazon.com/ec2/faqs/#How_many_instances_can_I_run_in_Amazon_EC2)

```
com.amazonaws.AmazonServiceException: Your quota allows for 0 more running instance(s). You requested at least 1 (Service: AmazonEC2; Status Code: 400; Error Code: InstanceLimitExceeded; Request ID: 859e85d7-0933-489f-8ff7-26734030bbab)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1160)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:748)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11598)
        at com.amazonaws.services.ec2.AmazonEC2Client.runInstances(AmazonEC2Client.java:5582)
        at nl.tudelft.in4303.grading.EC2Service.runAndWait(EC2Service.java:45)
        at nl.tudelft.in4303.grading.EC2Service.runSlave(EC2Service.java:62)
        at nl.tudelft.in4303.grading.Runner.runSlave(Runner.java:146)
        at nl.tudelft.in4303.grading.Runner.lambda$run$1(Runner.java:46)
        at nl.tudelft.in4303.grading.Runner$$Lambda$9/1575113400.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by MartijnDwars** [comment]
Solved by requesting an increase in instance limit (50).
